# action.yml
name: 'Github Pages Directory Listing'
description: 'dir'

author: 'tc012 + forked fromjayanta525'
branding:
  color: 'green'
  icon: 'upload-cloud'

inputs:
  FOLDER:
    description: 'folder to start index generations'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.FOLDER }}
